name: Deploy to GitHub Pages

# Trigger the workflow when there is a push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # The OS where the action will run

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the Node.js version you prefer (matches your package.json)

      # Set warnings to be warnings not errors
      - name: Set CI to false
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Set Git user name and email
        run: |
          git config --global user.email "sidneygmz@gmail.com"
          git config --global user.name "Sidney"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build and deploy the app using the predeploy and deploy scripts from package.json
      - name: Build and Deploy to GitHub Pages
        run: |
          npm run predeploy  # This will run npm run build (to build the project)
          npm run deploy     # This will deploy to GitHub Pages using gh-pages
        env:
          REACT_APP_TRAIN_APP_API_KEY: ${{ secrets.REACT_APP_TRAIN_APP_API_KEY }}  # Inject your API key if needed
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Step 5: Notify if the deploy fails (optional)
      - name: Deployment Status
        if: failure()
        run: echo "Deployment failed"
